#!/usr/bin/env python3
"""
Build docs_bundle.js from manifest.json + markdown files.
Usage (from project root):
  python doc/build_doc_bundle.py
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    doc_dir = Path(__file__).resolve().parent
    manifest_path = doc_dir / "manifest.json"
    output_path = doc_dir / "docs_bundle.js"

    manifest_raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    sections = manifest_raw.get("sections", [])
    if not isinstance(sections, list) or not sections:
        raise SystemExit("manifest.json has no sections array")

    content = {}
    for sec in sections:
        sec_id = sec.get("id")
        sec_file = sec.get("file")
        if not sec_id or not sec_file:
            raise SystemExit(f"Invalid section entry: {sec!r}")
        md_path = doc_dir / sec_file
        if not md_path.exists():
            raise SystemExit(f"Missing markdown file: {md_path}")
        content[str(sec_id)] = md_path.read_text(encoding="utf-8")

    payload = (
        "/* Auto-generated by doc/build_doc_bundle.py. */\n"
        "(function () {\n"
        "  window.NEBULA_DOC_MANIFEST = "
        + json.dumps(sections, ensure_ascii=False, indent=2)
        + ";\n"
        "  window.NEBULA_DOC_CONTENT = "
        + json.dumps(content, ensure_ascii=False, indent=2)
        + ";\n"
        "})();\n"
    )
    output_path.write_text(payload, encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
