#!/usr/bin/env python3
"""Generate js/example_batch_effect_data.js.

Synthetic omics-style dataset with a KNOWN batch effect and KNOWN biological
signal, used by the Nebula "Batch Effect" sub-tab demo loader:

  24 samples = 2 batches x 2 groups x 6 replicates (balanced: batch is NOT
  confounded with group), 500 features.

  log2 intensity = feature baseline + Treatment effect + batch location
                   + batch scale * (deviation from the biological mean) + noise

Deterministic: fixed seed, stdlib only. Re-run to regenerate the JS file.
"""

import json
import os
import random

SEED = 20260918
N_FEATURES = 500
N_REPS = 6
BASE_LOG2_MEAN = 22.0
BASE_LOG2_SD = 1.0
DE_FEATURES = 80
DE_LOG2FC = 1.2
BATCH2_SHIFT_MEAN = 0.70
BATCH2_SHIFT_SD = 0.30
BATCH1_SHIFT_SD = 0.10
SCALE_FEATURE_FRACTION = 0.60
SCALE_MEAN = 1.30
SCALE_SD = 0.12
NOISE_LOG2_SD = 0.25
MISSING_FRACTION = 0.03
NEG_LOG10 = 40.0


def build_samples():
    samples = []
    for rep in range(1, N_REPS + 1):
        for group_key, group_label in (("ctrl", "Control"), ("trt", "Treatment")):
            for batch_num in (1, 2):
                samples.append({
                    "id": "batch%d_%s_%d" % (batch_num, group_key, rep),
                    "group": group_label,
                    "batch": "Batch%d" % batch_num,
                    "treated": group_key == "trt",
                    "batch_num": batch_num,
                })
    return samples


def build_matrix(samples):
    n = len(samples)
    header = ["ID"] + [s["id"] for s in samples]
    rows = []
    missing_count = 0
    cell_count = 0

    for f in range(N_FEATURES):
        baseline = random.gauss(BASE_LOG2_MEAN, BASE_LOG2_SD)
        if f < DE_FEATURES // 2:
            bio_effect = DE_LOG2FC
        elif f < DE_FEATURES:
            bio_effect = -DE_LOG2FC
        else:
            bio_effect = 0.0

        batch_shift = {1: random.gauss(0.0, BATCH1_SHIFT_SD), 2: random.gauss(BATCH2_SHIFT_MEAN, BATCH2_SHIFT_SD)}
        if random.random() < SCALE_FEATURE_FRACTION:
            batch_scale = {1: 1.0, 2: max(1.0, random.gauss(SCALE_MEAN, SCALE_SD))}
        else:
            batch_scale = {1: 1.0, 2: 1.0}

        values = []
        for s in samples:
            biological = baseline + (bio_effect if s["treated"] else 0.0)
            b = s["batch_num"]
            log2_value = biological + batch_shift[b] + batch_scale[b] * random.gauss(0.0, NOISE_LOG2_SD)
            cell_count += 1
            # MNAR: sparser for the dimmest cells
            p_missing = MISSING_FRACTION * (1.6 - (log2_value - BASE_LOG2_MEAN) / 6.0)
            p_missing = min(0.30, max(0.001, p_missing))
            if random.random() < p_missing:
                values.append("")
                missing_count += 1
            else:
                values.append(str(int(round(2.0 ** log2_value))))
        rows.append(["P%04d" % (f + 1)] + values)

    stats = {
        "features": N_FEATURES,
        "de_features": DE_FEATURES,
        "missing_fraction": missing_count / float(cell_count) if cell_count else 0.0,
    }
    return header, rows, stats


def build_meta(samples):
    header = ["Sample_ID", "Group", "Batch"]
    rows = [[s["id"], s["group"], s["batch"]] for s in samples]
    return header, rows


def to_js(header, rows, stats, meta_header, meta_rows):
    matrix = {"headers": header, "rows": rows}
    meta = {"headers": meta_header, "rows": meta_rows}
    lines = [
        "// Batch-effect example: %d features x %d samples, 2 batches x 2 groups," % (stats["features"], len(meta_rows)),
        "// with a known additive + scale batch effect and %d truly group-different features." % stats["de_features"],
        "// Auto-generated by scripts/build_batch_effect_example.py (seed %d) - do not edit by hand." % SEED,
        "(function () {",
        "    var _matrix = " + json.dumps(matrix, separators=(",", ":")) + ";",
        "    var _meta = " + json.dumps(meta, separators=(",", ":")) + ";",
        "",
        "    function buildTsv(spec) {",
        "        var lines = [spec.headers.join('\\t')];",
        "        for (var i = 0; i < spec.rows.length; i++) lines.push(spec.rows[i].join('\\t'));",
        "        return lines.join('\\n');",
        "    }",
        "",
        "    var _matrixTsv = null;",
        "    var _metaTsv = null;",
        "    if (!Object.getOwnPropertyDescriptor(window, 'batchEffectExampleMatrixText')) {",
        "        Object.defineProperty(window, 'batchEffectExampleMatrixText', {",
        "            get: function () { if (_matrixTsv === null) _matrixTsv = buildTsv(_matrix); return _matrixTsv; },",
        "            configurable: true",
        "        });",
        "    }",
        "    if (!Object.getOwnPropertyDescriptor(window, 'batchEffectExampleMetaText')) {",
        "        Object.defineProperty(window, 'batchEffectExampleMetaText', {",
        "            get: function () { if (_metaTsv === null) _metaTsv = buildTsv(_meta); return _metaTsv; },",
        "            configurable: true",
        "        });",
        "    }",
        "})();",
        "",
    ]
    return "\n".join(lines)


def main():
    random.seed(SEED)
    samples = build_samples()
    header, rows, stats = build_matrix(samples)
    meta_header, meta_rows = build_meta(samples)
    js = to_js(header, rows, stats, meta_header, meta_rows)

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(root, "js", "example_batch_effect_data.js")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(js)

    print("wrote %s (%d bytes)" % (out_path, len(js)))
    print("matrix: %d features x %d samples" % (len(rows), len(samples)))
    print("group-different features: %d (log2FC +/-%.2f)" % (stats["de_features"], DE_LOG2FC))
    print("batches: 2 (location shift mean %.2f, scale factor mean %.2f on %.0f%% of features)"
          % (BATCH2_SHIFT_MEAN, SCALE_MEAN, SCALE_FEATURE_FRACTION * 100))
    print("missing cells: %.2f%%" % (stats["missing_fraction"] * 100))


if __name__ == "__main__":
    main()
